### ISSUE TITLE
Why preprocess the global plan using the elatic band algorithm? What is the purpose of doing this?

### ISSUE THREAD

**Issue by gycyr** [gKouros/rsband_local_planner#17]
if(!ebandPlanner_->setPlan(transformedPlan_))
    {
      costmapROS_->resetLayers();
      if(!ebandPlanner_->setPlan(transformedPlan_))
      {
        ROS_ERROR("Setting plan to Elastic Band failed!");
        return false;
      }
    }

    planStartEndCounters_ = planStartEndCounters;

    if (!ebandPlanner_->optimizeBand())
      ROS_WARN("Optimization of eband failed!");

**Comment by gycyr** [comment]
Thanks in advance.

**Comment by gkouros** [comment]
Hi gycyr,
I added the elastic band algorithm to rsband planner in order to achieve dynamic obstacle avoidance. Of course, you can try it without the elastic band. It shouldn't be too hard to test.
Best regards,
George

**Comment by gycyr** [comment]
I understand. Thank you for your response.
