### ISSUE TITLE
I want to simulate running in the stage, can you provide a reference launch file

### ISSUE THREAD

**Issue by touchmii** [gKouros/rsband_local_planner#18]
i config eband local planner as local planner with diff car simulate all going well，but use rsband with carlike model ，The car could not turn around and had to go straight。

**Comment by gkouros** [comment]
In the following link, you can find a configuration I used for simulations in Gazebo and STDR.

https://github.com/pandora-auth-ros-pkg/pandora_navigation/blob/indigo-devel/pandora_monstertruck_2dnav/config/local_planners/rsband/base_local_planner_params.yaml

Hope that helps.
