### ISSUE TITLE
error with catkin_make

### ISSUE THREAD

**Issue by offtaste** [gKouros/rsband_local_planner#19]
Hey I wanted to try out your planer as an alternative to the teb_local.
I installed all the named dependencies and double checked that. 
but when I try to catkin_make, I do now get the error, that there is a header.h missing:

In file included from /home/linus/catkin_ws/src/rsband_local_planner/src/fuzzy_ptc.cpp:38:0:
/home/linus/catkin_ws/src/rsband_local_planner/include/rsband_local_planner/fuzzy_ptc.h:52:10: fatal error: fl/Headers.h: File or directory not found
 #include <fl/Headers.h>
          ^~~~~~~~~~~~~~
compilation terminated.

could deal with fuzzylite, but as I mentioned, I installed and also updated it.

**Comment by gkouros** [comment]
Make sure you installed the right version of fuzzylite.

**Comment by offtaste** [comment]
I took it directly with sudo apt-get
How to get a more actual version?

**Comment by gkouros** [comment]
Look in my README.md. There are instructions to install fuzzylite-6 from source.

**Comment by offtaste** [comment]
now I feel dumb. Was a big hustle to do it according to that instruction (SSH struggle) but at the end, it did work. THX!!
