### ISSUE TITLE
Backward motion parameter

### ISSUE THREAD

**Issue by KoushikRaghav** [gKouros/rsband_local_planner#20]
What parameter should we use to enable backward motion?

**Comment by gkouros** [comment]
It's enabled already. To go backwards, the reeds-shepp planner needs to make a plan for moving backwards and then the path tracking controller will know what to do.

**Comment by darshan-d022** [comment]
Hi,
I have tried setting the min_lin_x param to a -ve value, still my cmd_vel doesnt publish -ve linear x values. Can you please let me know if there is any additional param to enable backwards motion?? 
Note: I have tried to change the min and max values in the .cfg file for min_lin_x param. Still doesnt make any change.

**Comment by gkouros** [comment]
Backward motion should work without any parameter changes. If it doesn't, it's probably a controller issue. You can observe the Twist commands RSBandPLanner outputs and whether linear.x gets negative values. If it does, then you should look into what happens in the controller receiving the Twist commands.

**Comment by KoushikRaghav** [comment]
Setting the param emergency_planning to false publishes negative linear x
