### ISSUE TITLE
Question about StartToEnd Strategy

### ISSUE THREAD

**Issue by LotfiZ** [gKouros/rsband_local_planner#22]
Hi George, 

First, great idea to combine eband planner and rs planner in a context of a local planner for Ackermann models. Amazing work ! 

Correct me if i'm wrong but the StartToEnd Strategy use the RS planner only for the start and end pose derived from the eband planner. However, knowing that the RS planner does not perform a path searching ( as global planner do ), how in this case he will find the best path between the two poses without a collision check between them ? 

Maybe i missed something, and i'll really appreciate if you can clarify this point for me.

Thank you,

**Comment by gkouros** [comment]
Hi.

Using StartToEnd planner does not make much sense in combination with a global planner. I added it mostly for some experiments where the global path is simply the start and the goal pose without any inbetween poses. I personally mainly used the StartToNext strategy. Also, I suggest you look into [teb_local_planner](https://github.com/rst-tu-dortmund/teb_local_planner) if you haven't already. It works much better than my approach.

I hope that helps.

**Comment by LotfiZ** [comment]
Thank you for the quick response George ! 

Im digging into your approach to see how i can use your implementation of the rs planner as a global planner. I already read your comment to the ticket opened in your rs planner wrapper concerning using it as global planner then i saw the StartToEnd Strategy and i was little bit confused. Now i understand ! A big thanks to you ! 

Best regards
