### ISSUE TITLE
Question about output

### ISSUE THREAD

**Issue by Alegado** [gKouros/rsband_local_planner#23]
Hi,
I am trying to use your planner, but I can't really understand how to interpret what is published on /cmd_vel. I can see that linear.x, linear.y and angular.z are assigned values, but I'm not really sure what they mean. My vehicle is controlled by giving it linear speed and steering angle of the wheels. Obviously no problem with the meaning of linear.x, but not really sure how to interpret linear.y and angular.z. I noticed also that if I use the counter steering mode linear.y is always zero. Thanks for any help, I'm not sure if I should ask here or on the eband page, sorry in advance if it's the wrong place.

**Comment by gkouros** [comment]
You basically have to translate the Twist message to a speed and steering command or just modify the code to publish the speed and steering command. Have a look at this [controller implementation](https://github.com/pandora-auth-ros-pkg/pandora_hardware_interface/blob/fad9c9a91324815b78cfa161ec96ff296090674c/pandora_monstertruck_hardware_interface/monstertruck_steer_drive_controller/src/monstertruck_steer_drive_controller.cpp#L302) to figure out how to do the conversion.

**Comment by Alegado** [comment]
Thanks,I'll have a look into that, it's just that in Ackermann drives I studied it all depends on linear x speed and angular z speed, no mention of linear y speed, so I was kinda puzzled.

**Comment by gkouros** [comment]
I developed the planner for a 4WS robot and because you can move the 
front wheels in the same direction as the real wheels you can achieve 
both a longitudinal (x) and a lateral speed (y) component and basically 
move diagonally. However, a simple ackermann drive can have only the 
longitudinal and angular speeds as you said.

**Comment by Alegado** [comment]
Ok thanks, it all makes sense now, thanks a lot.
